# Define wealth chat request configuration
financial_planner_req_config = {
    "question": "",
    "tools": {
        "FinancialPlannerTool":{
            "client_name": "str"
        }
        },
    "restriction": {
        "categories": ["1"]
    }   
}

financial_planner_answer_format = """
Your Final Answer should be extremely detailed. Use the full output from the FinancialPlannerTool as it is without summarizing it or paraphrasing.
The Answer should have Considerations, Observations and Calculations in the following Format

Final Answer: ...
Considerations: ...
Observations: ...
Calculations: ...


Final Answer: ...
Considerations: ...
Observations: ...
Calculations: ....


Final Answer: ...
Considerations: ...
Observations: ...
Calculations: ...


Final Answer: ...
Considerations: ...
Observations: ...
Calculations: ...

"""
