# Define final answer format for top 3 titles
default_final_answer_format_top3titles = """You are an expert in drafting the output in the format below:
Titles:['Title1','Title2','Title3']

Here, Titles will be list of most relevant {num_results} Titles to be selected.
"""

# Define template for getting most relevant top 3 titles to the question
template_top3titles = "Given the query: {query}, rank the top {num_results} most relevant titles  from the following list :" "\n"+ "\n"+"{titles}" +"\n"+"{default_final_answer_format}"

# Define template for final answer format summary
default_final_answer_format_summary="""You are an expert in drafting the output in the format below:
Summary: ...
<INFORMATION USED>
URLs used: [URL1, URL2 ....]

URLs used should be a list of the URLs of ONLY the URLs where you created the summary.
<INFORMATION USED> is a delimeter between Summary generated by you and URLs used list.
"""

# Define template for getting summary of the content
template_summary = """Given the query: {query}, generate a summary from the following content:
{summary}

{default_final_answer_format}"""